// Source: packages/shared/types/api.ts
// Internalized to backend to fix Docker build (shared package not available in container)

// ============================================
// API Response Types
// ============================================

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: ApiError;
  meta?: PaginationMeta;
}

export interface ApiError {
  code: string;
  message: string;
}

export interface PaginationMeta {
  total: number;
  page: number;
  limit: number;
  hasMore: boolean;
}

// ============================================
// 統一錯誤代碼（合併 api.ts + index.ts 的定義）
// ============================================
export const ErrorCodes = {
  // 認證相關
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_INVALID_STATE: "AUTH_INVALID_STATE",
  AUTH_EXPIRED: "AUTH_EXPIRED",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT_FAILED: "AUTH_LOGOUT_FAILED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_OAUTH_URL_FAILED: "AUTH_OAUTH_URL_FAILED",
  AUTH_GET_USER_FAILED: "AUTH_GET_USER_FAILED",
  AUTH_REFRESH_FAILED: "AUTH_REFRESH_FAILED",

  // 權限相關
  PERM_DENIED: "PERM_DENIED",
  PERM_ROLE_REQUIRED: "PERM_ROLE_REQUIRED",

  // 資源相關
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",

  // 使用者相關
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_SETTINGS_FETCH_FAILED: "USER_SETTINGS_FETCH_FAILED",
  USER_SETTINGS_UPDATE_FAILED: "USER_SETTINGS_UPDATE_FAILED",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  SLACK_ID_EXISTS: "SLACK_ID_EXISTS",

  // 任務相關
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_NOT_UNCLAIMED: "TASK_NOT_UNCLAIMED",
  TASK_ALREADY_CLAIMED: "TASK_ALREADY_CLAIMED",
  TASK_FETCH_FAILED: "TASK_FETCH_FAILED",
  TASK_UPDATE_FAILED: "TASK_UPDATE_FAILED",
  TASK_CREATE_FAILED: "TASK_CREATE_FAILED",
  TASK_DELETE_FAILED: "TASK_DELETE_FAILED",
  TASK_CLAIM_FAILED: "TASK_CLAIM_FAILED",
  TASK_UNCLAIM_FAILED: "TASK_UNCLAIM_FAILED",
  TASK_STATUS_UPDATE_FAILED: "TASK_STATUS_UPDATE_FAILED",
  TASK_PROGRESS_UPDATE_FAILED: "TASK_PROGRESS_UPDATE_FAILED",
  TASK_NOTES_FETCH_FAILED: "TASK_NOTES_FETCH_FAILED",
  TASK_NOTE_CREATE_FAILED: "TASK_NOTE_CREATE_FAILED",
  TASK_PROGRESS_FETCH_FAILED: "TASK_PROGRESS_FETCH_FAILED",
  TASK_PROGRESS_CREATE_FAILED: "TASK_PROGRESS_CREATE_FAILED",

  // 里程碑相關
  MILESTONE_NOT_FOUND: "MILESTONE_NOT_FOUND",
  MILESTONE_CREATE_FAILED: "MILESTONE_CREATE_FAILED",
  MILESTONE_UPDATE_FAILED: "MILESTONE_UPDATE_FAILED",
  MILESTONE_DELETE_FAILED: "MILESTONE_DELETE_FAILED",
  MILESTONES_FETCH_FAILED: "MILESTONES_FETCH_FAILED",

  // 專案相關
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECTS_FETCH_FAILED: "PROJECTS_FETCH_FAILED",
  PROJECT_FETCH_FAILED: "PROJECT_FETCH_FAILED",
  PROJECT_CREATE_FAILED: "PROJECT_CREATE_FAILED",
  PROJECT_UPDATE_FAILED: "PROJECT_UPDATE_FAILED",
  PROJECT_DELETE_FAILED: "PROJECT_DELETE_FAILED",
  PROJECT_STATS_FAILED: "PROJECT_STATS_FAILED",
  GANTT_FETCH_FAILED: "GANTT_FETCH_FAILED",
  INVALID_DATE_RANGE: "INVALID_DATE_RANGE",

  // 員工相關
  EMPLOYEE_NOT_FOUND: "EMPLOYEE_NOT_FOUND",
  EMPLOYEES_FETCH_FAILED: "EMPLOYEES_FETCH_FAILED",
  EMPLOYEE_FETCH_FAILED: "EMPLOYEE_FETCH_FAILED",
  EMPLOYEE_CREATE_FAILED: "EMPLOYEE_CREATE_FAILED",
  EMPLOYEE_UPDATE_FAILED: "EMPLOYEE_UPDATE_FAILED",
  EMPLOYEE_DELETE_FAILED: "EMPLOYEE_DELETE_FAILED",

  // 進度相關
  PROGRESS_FETCH_FAILED: "PROGRESS_FETCH_FAILED",
  PROGRESS_TODAY_FAILED: "PROGRESS_TODAY_FAILED",
  PROGRESS_STATS_FAILED: "PROGRESS_STATS_FAILED",
  PROGRESS_CREATE_FAILED: "PROGRESS_CREATE_FAILED",

  // 儀表板相關
  DASHBOARD_STATS_FAILED: "DASHBOARD_STATS_FAILED",
  DASHBOARD_WORKLOADS_FAILED: "DASHBOARD_WORKLOADS_FAILED",

  // 工時記錄相關
  TIME_ENTRY_NOT_FOUND: "TIME_ENTRY_NOT_FOUND",
  TIME_ENTRIES_FETCH_FAILED: "TIME_ENTRIES_FETCH_FAILED",
  TIME_ENTRY_FETCH_FAILED: "TIME_ENTRY_FETCH_FAILED",
  TIME_ENTRY_CREATE_FAILED: "TIME_ENTRY_CREATE_FAILED",
  TIME_ENTRY_UPDATE_FAILED: "TIME_ENTRY_UPDATE_FAILED",
  TIME_ENTRY_DELETE_FAILED: "TIME_ENTRY_DELETE_FAILED",
  TIME_ENTRY_BATCH_FAILED: "TIME_ENTRY_BATCH_FAILED",
  TIME_ENTRY_TODAY_FAILED: "TIME_ENTRY_TODAY_FAILED",
  TIME_ENTRY_WEEK_FAILED: "TIME_ENTRY_WEEK_FAILED",

  // 工時類別相關
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORIES_FETCH_FAILED: "CATEGORIES_FETCH_FAILED",
  CATEGORY_FETCH_FAILED: "CATEGORY_FETCH_FAILED",
  CATEGORY_CREATE_FAILED: "CATEGORY_CREATE_FAILED",
  CATEGORY_UPDATE_FAILED: "CATEGORY_UPDATE_FAILED",
  CATEGORY_DELETE_FAILED: "CATEGORY_DELETE_FAILED",
  CATEGORY_DEACTIVATE_FAILED: "CATEGORY_DEACTIVATE_FAILED",
  CATEGORY_ACTIVATE_FAILED: "CATEGORY_ACTIVATE_FAILED",
  CATEGORIES_INIT_FAILED: "CATEGORIES_INIT_FAILED",

  // 工時統計相關
  TIME_STATS_PROJECT_FAILED: "TIME_STATS_PROJECT_FAILED",
  TIME_STATS_EMPLOYEE_FAILED: "TIME_STATS_EMPLOYEE_FAILED",
  TIME_STATS_MY_FAILED: "TIME_STATS_MY_FAILED",
  TIME_STATS_MONTHLY_FAILED: "TIME_STATS_MONTHLY_FAILED",
  TIME_STATS_DASHBOARD_FAILED: "TIME_STATS_DASHBOARD_FAILED",
  TIME_STATS_PENDING_FAILED: "TIME_STATS_PENDING_FAILED",

  // GitLab 相關
  GITLAB_LINK_FAILED: "GITLAB_LINK_FAILED",
  GITLAB_UNLINK_FAILED: "GITLAB_UNLINK_FAILED",
  GITLAB_INSTANCES_FETCH_FAILED: "GITLAB_INSTANCES_FETCH_FAILED",
  GITLAB_INSTANCE_NOT_FOUND: "GITLAB_INSTANCE_NOT_FOUND",
  GITLAB_INSTANCE_FETCH_FAILED: "GITLAB_INSTANCE_FETCH_FAILED",
  GITLAB_INSTANCE_CREATE_FAILED: "GITLAB_INSTANCE_CREATE_FAILED",
  GITLAB_INSTANCE_UPDATE_FAILED: "GITLAB_INSTANCE_UPDATE_FAILED",
  GITLAB_INSTANCE_DELETE_FAILED: "GITLAB_INSTANCE_DELETE_FAILED",
  GITLAB_TEST_FAILED: "GITLAB_TEST_FAILED",
  GITLAB_WEBHOOK_REGEN_FAILED: "GITLAB_WEBHOOK_REGEN_FAILED",
  GITLAB_CONNECTIONS_FETCH_FAILED: "GITLAB_CONNECTIONS_FETCH_FAILED",
  GITLAB_CONNECTION_NOT_FOUND: "GITLAB_CONNECTION_NOT_FOUND",
  GITLAB_CONNECTION_INACTIVE: "GITLAB_CONNECTION_INACTIVE",
  GITLAB_CONNECTION_DELETE_FAILED: "GITLAB_CONNECTION_DELETE_FAILED",
  GITLAB_SETTINGS_UPDATE_FAILED: "GITLAB_SETTINGS_UPDATE_FAILED",
  GITLAB_OAUTH_URL_FAILED: "GITLAB_OAUTH_URL_FAILED",
  GITLAB_SYNC_FAILED: "GITLAB_SYNC_FAILED",
  GITLAB_ACTIVITIES_FETCH_FAILED: "GITLAB_ACTIVITIES_FETCH_FAILED",
  GITLAB_SUMMARY_FAILED: "GITLAB_SUMMARY_FAILED",
  GITLAB_ACTIVITY_NOT_FOUND: "GITLAB_ACTIVITY_NOT_FOUND",
  GITLAB_ACTIVITY_FETCH_FAILED: "GITLAB_ACTIVITY_FETCH_FAILED",
  GITLAB_CONVERT_FAILED: "GITLAB_CONVERT_FAILED",
  GITLAB_BATCH_CONVERT_FAILED: "GITLAB_BATCH_CONVERT_FAILED",
  GITLAB_LINK_TASK_FAILED: "GITLAB_LINK_TASK_FAILED",
  GITLAB_MAPPINGS_FETCH_FAILED: "GITLAB_MAPPINGS_FETCH_FAILED",
  GITLAB_MAPPING_CREATE_FAILED: "GITLAB_MAPPING_CREATE_FAILED",
  GITLAB_MAPPING_DELETE_FAILED: "GITLAB_MAPPING_DELETE_FAILED",
  GITLAB_SYNC_FROM_FAILED: "GITLAB_SYNC_FROM_FAILED",
  GITLAB_SYNC_TO_FAILED: "GITLAB_SYNC_TO_FAILED",
  GITLAB_ISSUE_SEARCH_FAILED: "GITLAB_ISSUE_SEARCH_FAILED",
  GITLAB_ISSUE_CREATE_FAILED: "GITLAB_ISSUE_CREATE_FAILED",

  // Slack 相關
  SLACK_LINK_FAILED: "SLACK_LINK_FAILED",
  SLACK_UNLINK_FAILED: "SLACK_UNLINK_FAILED",
  SLACK_INTERACTION_FAILED: "SLACK_INTERACTION_FAILED",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",

  // 健康檢查相關
  SERVICE_NOT_READY: "SERVICE_NOT_READY",

  // 驗證相關
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VALIDATION_REQUIRED: "VALIDATION_REQUIRED",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // 資料庫相關
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  NOT_FOUND: "NOT_FOUND",
  INVALID_REFERENCE: "INVALID_REFERENCE",
  DATABASE_ERROR: "DATABASE_ERROR",

  // 網路與伺服器
  SERVER_ERROR: "SERVER_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
