-- This migration is a duplicate of 20260305000000_add_oauth_state.
-- Replaced with no-op to fix CI (table already exists from previous migration).
-- See: https://www.prisma.io/docs/guides/database/production-troubleshooting
